# GitHub Actions Documentation: https://docs.github.com/en/actions

name: "build"

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request:
    branches:
      - "main"

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  functional-tests:
    name: "Functional tests"
    runs-on: "ubuntu-latest"
    container:
      image: "ubuntu:22.04"
      volumes:
        - "${{ github.workspace }}:/ecma_intl"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v3"

      - name: "Install ICU"
        run: |
          set -e
          apt-get update
          apt-get install -y build-essential clang git
          cd /tmp
          git clone https://github.com/unicode-org/icu.git
          cd icu/icu4c/source/
          git checkout release-71-1
          ./runConfigureICU Linux
          make -j$(nproc)
          make install

      - name: "Install PHP"
        run: |
          set -e
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
          apt-get -y install build-essential php8.1 php8.1-dev tzdata
          dpkg-reconfigure --frontend noninteractive tzdata
          $(php-config --php-binary) --version
          phpize --version

      - name: "Build and install ecma_intl"
        run: |
          set -e
          cd /ecma_intl
          phpize
          ./configure --enable-ecma_intl
          make -j$(nproc)
          make install
          echo "extension=ecma_intl.so" > "$(php-config --ini-dir)/99-ecma_intl.ini"
          "$(php-config --php-binary)" --ri ecma_intl

      - name: "Run tests"
        run: |
          set -e
          export PHP_BINARY="$(php-config --php-binary)"
          $PHP_BINARY run-tests.php -q -P --show-diff tests
